[package]
name = "u2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = { version = "0.7.0", features = ["user-operations", "derive"] }
rand = "0.8.5"
